# Generated by Django 4.0.1 on 2022-01-25 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=191, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('weight', models.FloatField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=191, unique=True)),
                ('min_price', models.FloatField(blank=True)),
                ('max_price', models.FloatField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=191, null=True)),
                ('owner', models.CharField(blank=True, max_length=191)),
                ('breed', models.PositiveIntegerField(blank=True, default='', null=True)),
                ('age', models.PositiveIntegerField(blank=True, default='', null=True)),
                ('weight', models.FloatField(blank=True, default='', null=True)),
                ('color', models.IntegerField(blank=True, default='', null=True)),
                ('entry_date', models.DateTimeField(blank=True, default='', null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.doctor')),
                ('examination', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.medicalexamination')),
            ],
        ),
    ]
