# Generated by Django 4.0.1 on 2022-01-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.PositiveIntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.FloatField(blank=True, default='', null=True),
        ),
    ]
