# Generated by Django 3.2.9 on 2021-12-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_auto_20211209_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='entry_date',
            field=models.DateField(blank=True),
        ),
    ]
