# Generated by Django 3.2.9 on 2021-12-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_alter_animal_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='entry_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
