# Generated by Django 3.2.9 on 2022-01-05 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_auto_20220105_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.doctor'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='examination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.medicalexamination'),
        ),
    ]
