# Generated by Django 4.0.1 on 2022-01-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_auto_20220105_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
