# Generated by Django 3.2.3 on 2021-11-05 08:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2021, 11, 5, 8, 5, 23, 541489, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authuser',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2021, 11, 5, 8, 5, 38, 237571, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
    ]
