# Generated by Django 3.2.3 on 2021-11-05 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211105_1205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthUser',
            new_name='Account',
        ),
    ]
