# Generated by Django 3.1.7 on 2021-11-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
